### ISSUE TITLE
Tareas desordenadas en reporte

### ISSUE THREAD

**Issue by kodamirmo** [kodamirmo/GoAndSeeIssueTracker#1]
Las pruebas se desorganizan al verlas en pdf desde el historial.  En vez de darme un orden descendente de las pruebas el orden es: 7,5,1,3,2,4,6. 
![screen shot 2016-02-29 at 7 54 38 pm](https://cloud.githubusercontent.com/assets/1815586/13415167/51dc9f84-df1e-11e5-8dcd-6ba99eaa517a.png)

**Comment by kodamirmo** [comment]
Lo mismo pasará con las locaciones.

**Comment by sergio-nnz** [comment]
Hola Irvin, siento que deberías darle amor a este issue porque la lista mas reciente que quieren probar son de 70 preguntas con categorias, como el programa realmente no categoriza los task la única manera para llevar un orden al hacer un reporte es enumerandolos, y cuando enseñemos los datos se va a ver muy bien si están bien ordenados. Aun nos queda tiempo entonces aun no es necesario la desvelada

**Comment by sergio-nnz** [comment]
Esto se repite

**Comment by kodamirmo** [comment]
Solved
