### ISSUE TITLE
Cuando editas un gemba y el tiempo para completar esta en "weeks", se hace un cambio en el valor.

### ISSUE THREAD

**Issue by sergio-nnz** [kodamirmo/GoAndSeeIssueTracker#10]
![editchangeoriginal](https://cloud.githubusercontent.com/assets/17553732/13505559/87e99b56-e12e-11e5-9b65-37a63925a2c9.PNG)
![editchange](https://cloud.githubusercontent.com/assets/17553732/13505564/8c8cc412-e12e-11e5-8e78-66b6040770de.PNG)

---

![editchange3](https://cloud.githubusercontent.com/assets/17553732/13505569/8faba3de-e12e-11e5-9c22-375fb73cb874.PNG)
![editchange4](https://cloud.githubusercontent.com/assets/17553732/13505571/94e6e8d6-e12e-11e5-8ffb-248cb4b25788.PNG)

---

![editchange6](https://cloud.githubusercontent.com/assets/17553732/13505584/9dc2fdd2-e12e-11e5-9a1b-87374956e834.PNG)
![editchange5](https://cloud.githubusercontent.com/assets/17553732/13505579/9918c9a6-e12e-11e5-8e17-cb4491c80901.PNG)

**Comment by kodamirmo** [comment]
Esto es por lo pronto lo mas critico de todo.

**Comment by sergio-nnz** [comment]
Esto se repite

**Comment by kodamirmo** [comment]
Solved
