### ISSUE TITLE
El nombre de los audios que sirven como referencia en el ipad siempre son "Audio 1"

### ISSUE THREAD

**Issue by sergio-nnz** [kodamirmo/GoAndSeeIssueTracker#13]
![20160316_113226](https://cloud.githubusercontent.com/assets/17553732/13824649/27abc56e-eb6c-11e5-9e3b-68f851305fbb.jpg)

**Comment by kodamirmo** [comment]
Solved in dfa9acee644bc21c054bf816988bfebcd0fe969f
