### ISSUE TITLE
Extension de PDF

### ISSUE THREAD

**Issue by kodamirmo** [kodamirmo/GoAndSeeIssueTracker#2]
Los PDF no se guardan con extension pdf 
![screen shot 2016-02-29 at 7 55 49 pm](https://cloud.githubusercontent.com/assets/1815586/13415206/963845a2-df1e-11e5-8fc0-7f425a382935.png)

**Comment by kodamirmo** [comment]
Los archivos ya son generados como PDF, solo le tienes que poner Guardar.  Podríamos hacer que se descarguen automáticamente en vez de que se visualicen.

**Comment by sergio-nnz** [comment]
Esto se repite

**Comment by kodamirmo** [comment]
Duplicado de #16
