### ISSUE TITLE
En Android no se abren los PDFs

### ISSUE THREAD

**Issue by kodamirmo** [kodamirmo/GoAndSeeIssueTracker#3]
En Android no se abren los PDFs
![screen shot 2016-02-29 at 7 59 00 pm](https://cloud.githubusercontent.com/assets/1815586/13415264/023af59c-df1f-11e5-8f86-1dd330695f23.png)

**Comment by kodamirmo** [comment]
¿Que gemba es? @sergio-nnz

**Comment by sergio-nnz** [comment]
Era en prueba2, ahorita ese gemba lo tengo desabilitado

**Comment by sergio-nnz** [comment]
Se repite

**Comment by kodamirmo** [comment]
Duplicado de #16
