### ISSUE TITLE
Entrada duplicada en el historial

### ISSUE THREAD

**Issue by kodamirmo** [kodamirmo/GoAndSeeIssueTracker#8]
Cuando se subió una auditoria hubo error en iPhone, se volvió a subir y aprecio 2 veces en el historial. 
![screen shot 2016-02-29 at 8 09 38 pm](https://cloud.githubusercontent.com/assets/1815586/13415435/6cd440a6-df20-11e5-97d9-c4d53cedf50d.png)
![screen shot 2016-02-29 at 8 09 43 pm](https://cloud.githubusercontent.com/assets/1815586/13415436/6d08966c-df20-11e5-92cb-9f91b6439384.png)

**Comment by kodamirmo** [comment]
Permitir solo 1 entrada en el historial por auditoria.

**Comment by sergio-nnz** [comment]
No se repite

**Comment by kodamirmo** [comment]
Solved
